version: '2.3'
services:
  app:
    container_name: app 
    restart: always
    build: .
    runtime: nvidia
    ports:
      - 9191:9191
    volumes:
      - .:/faster_rcnn
      - <local model path>:/faster_rcnn/prod_models/model.pth
    command: python obj_detect.py